using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;

public class ScrollViewController : MonoBehaviour
{
    public ScrollRect scrollRect; // ScrollRect ФФЦїГЭЦЎ
    public RectTransform content; // ScrollViewРЧ Content
    public RectTransform selectedButton; // МБХУЕШ ЙіЦАРЧ RectTransform

    public ButtonSelectController buttonSelectController;

    private void Start()
    {
        buttonSelectController = GetComponent<ButtonSelectController>();
    }

    private void Update()
    {
        if (EventSystem.current.currentSelectedGameObject != null)
        {
            if (buttonSelectController.tagetButtonList.Contains(EventSystem.current.currentSelectedGameObject.GetComponent<Button>()))
            {
                selectedButton = EventSystem.current.currentSelectedGameObject.transform.parent.GetComponent<RectTransform>();
                CenterOnButton();
            }
        }
    }

    public void CenterOnButton()
    {
        // Viewport ГєРЬПЭ Content ГєРЬ АЁСЎПРБт
        float viewportHeight = scrollRect.viewport.rect.height;
        float contentHeight = content.rect.height;

        // МБХУЕШ ЙіЦАРЧ anchoredPosition.y ЛчПы
        float buttonCenterY = -selectedButton.anchoredPosition.y; // НКХЉЗб ЙцЧтПЁ ЕћЖѓ ЙнРќ ЧЪПф

        // Content ГєРЬПЁМ­ ЙіЦА РЇФЁ КёРВ АшЛъ
        float normalizedPositionY = 1 - ((buttonCenterY - (viewportHeight / 2)) / (contentHeight - viewportHeight));

        // ScrollRectРЧ normalizedPosition МГСЄ
        scrollRect.normalizedPosition = new Vector2(scrollRect.normalizedPosition.x, Mathf.Clamp01(normalizedPositionY));
    }

}
